language: python
python:
  - '3.7'

before_script:
  - pip install -r requirements.txt

env:
  global:
    - MOZ_HEADLESS=1
    - DJANGO_SETTINGS_MODULE='PlanniTeam.settings.travis'
    - SECRET_KEY='dhj4f6d^1pk$ufqj#!oere!3t3j4@$g*60&j)zn4i_y+0yi7dl'

services:
  - postgresql

script:
  - python ./manage.py test

addons:
  firefox: latest
  apt:
    packages:
      firefox-geckodriver

branches:
  only:
    - dev